MOVE_MAPPING={
    [0] = "bomb",
    [1] = "crush",
    [2] = "nado",
    [3] = "wbounce",
    [4] = "spin",
    [5] = "rkick",
    [6] = "djump",
    [7] = "wclimb",
    [8] = "bdance",
    [9] = "bodyslam",
    [10] = "staunt",
    [11] = "taunt",
    [12] = "grab",
    [13] = "sjump",
    [14] = "ucut",
    [15] = "mach4",
}